root: true
extends: standard
rules:
  indent:
    - error
    - 4
  camelcase: off
  padded-blocks: off
  operator-linebreak: off
  no-throw-literal: off

  # We replicate the eslint-config-semistandard rules here instead of
  # extending that config, since it is poorly maintained.
  semi:
    - 2
    - always
  no-extra-semi: 2
